name: bespoken
favicon: null
layout_spectrum: 0.06810036
typography_spectrum: 0.7204301
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Bespoken Management
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#323232'
    - '#edbe8b'
    - '#c4a47c'
    - '#735c46'
    - '#9b896c'
  brandStrength: 0.8136081919074059
  lightness: 0.1505376
  saturation: 0.7634408
  rhythmicContrast: 0.609319
purpose: []
