name: bespoken
favicon: null
layout_spectrum: 0.7369131054729223
typography_spectrum: 0.6165769575163722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8136081919074059
  lightness: 0.3529714331962168
  saturation: 0.20637881802394986
  rhythmicContrast: 0.04056926490738988
purpose: []
